[project]
name = "pythonic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keras>=3.11.3",
    "numpy>=2.3.1",
    "typing>=3.10.0.0",
]
